// start code
export default [
  {
    id: "custom",
    label: "سفارشی",
    title: "سفارشی",
    description: "برای سازمان‌هایی که به امکانات اختصاصی نیاز دارند.",
    bgSrc: "/images/phone-background.png",
    features: [
      "ویژگی ۱",
      "ویژگی ۲",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
    ],
    ctaLabel: "اطلاعات بیشتر",
    ctaHref: "#custom",
    badge: "اشتراک‌های منرو •",
  },
  {
    id: "menroPlus",
    label: "منرو+",
    title: "منرو+",
    description: "ویژه تیم‌های رو به رشد.",
    bgSrc: "/images/phone-background.png",
    features: [
      "ویژگی ۱",
      "ویژگی ۲",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
    ],
    ctaLabel: "اطلاعات بیشتر",
    ctaHref: "#menroPlus",
    badge: "اشتراک‌های منرو •",
  },
  {
    id: "pro",
    label: "حرفه‌ای",
    title: "حرفه‌ای",
    description: "انعطاف‌پذیر و اقتصادی برای بیشتر رستوران‌ها.",
    bgSrc: "/images/phone-background.png",
    features: [
      "ویژگی ۱",
      "ویژگی ۲",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
    ],
    ctaLabel: "اطلاعات بیشتر",
    ctaHref: "#pro",
    badge: "اشتراک‌های منرو •",
  },
  {
    id: "advanced",
    label: "پیشرفته",
    title: "پیشرفته",
    description: "شروعی قدرتمند برای رستوران‌هایی که به فکر آینده‌اند.",
    bgSrc: "/images/phone-background.png",
    features: [
      "ویژگی ۱",
      "ویژگی ۲",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
      "ویژگی ۳",
    ],
    ctaLabel: "اطلاعات بیشتر",
    ctaHref: "#advanced",
    badge: "اشتراک‌های منرو •",
  },
];
