// src/components/blog/blogData.js

export const categories = [
  "همه",
  "جدیدترین‌ها",
  "محبوب‌ترین‌ها",
  "پربازدیدترین‌ها",
  "داغ‌ترین‌ها",
];

export const blogs = [
  // --- جدیدترین‌ها (Newest) ---
  {
    id: 1,
    title: "طرز تهیه پاستا آلفردو با مرغ و قارچ",
    href: "/blog/1",
    coverSrc: "/images/blog-(1).png",
    readingMins: 5,
    category: "جدیدترین‌ها",
  },
  {
    id: 2,
    title: "راز یک پیتزای ایتالیایی خوشمزه",
    href: "/blog/2",
    coverSrc: "/images/blog-(2).png",
    readingMins: 6,
    category: "جدیدترین‌ها",
  },
  {
    id: 3,
    title: "طرز تهیه قهوه دمی در خانه",
    href: "/blog/3",
    coverSrc: "/images/blog-(3).png",
    readingMins: 3,
    category: "جدیدترین‌ها",
  },
  {
    id: 4,
    title: "بهترین دسرها برای مهمانی‌های تابستانی",
    href: "/blog/4",
    coverSrc: "/images/blog-(4).png",
    readingMins: 7,
    category: "جدیدترین‌ها",
  },
  {
    id: 5,
    title: "آموزش پخت نان سیر رستورانی",
    href: "/blog/5",
    coverSrc: "/images/blog-(1).png",
    readingMins: 4,
    category: "جدیدترین‌ها",
  },
  {
    id: 6,
    title: "چگونه سالاد سزار حرفه‌ای درست کنیم؟",
    href: "/blog/6",
    coverSrc: "/images/blog-(2).png",
    readingMins: 5,
    category: "جدیدترین‌ها",
  },

  // --- محبوب‌ترین‌ها (Most Popular) ---
  {
    id: 7,
    title: "بهترین رژیم غذایی برای ورزشکاران",
    href: "/blog/7",
    coverSrc: "/images/blog-(3).png",
    readingMins: 8,
    category: "محبوب‌ترین‌ها",
  },
  {
    id: 8,
    title: "نکاتی برای نگهداری طولانی‌مدت سبزیجات",
    href: "/blog/8",
    coverSrc: "/images/blog-(4).png",
    readingMins: 4,
    category: "محبوب‌ترین‌ها",
  },
  {
    id: 9,
    title: "۵ اشتباه رایج در پخت برنج",
    href: "/blog/9",
    coverSrc: "/images/blog-(1).png",
    readingMins: 5,
    category: "محبوب‌ترین‌ها",
  },
  {
    id: 10,
    title: "طرز تهیه یک صبحانه مقوی و سریع",
    href: "/blog/10",
    coverSrc: "/images/blog-(2).png",
    readingMins: 3,
    category: "محبوب‌ترین‌ها",
  },
  {
    id: 11,
    title: "ادویه‌های ضروری در هر آشپزخانه ایرانی",
    href: "/blog/11",
    coverSrc: "/images/blog-(3).png",
    readingMins: 6,
    category: "محبوب‌ترین‌ها",
  },
  {
    id: 12,
    title: "تکنیک‌های طلایی برای مزه‌دار کردن جوجه کباب",
    href: "/blog/12",
    coverSrc: "/images/blog-(4).png",
    readingMins: 7,
    category: "محبوب‌ترین‌ها",
  },

  // --- پربازدیدترین‌ها (Most Visited) ---
  {
    id: 13,
    title: "چگونه گوشت را سریع‌تر بپزیم؟",
    href: "/blog/13",
    coverSrc: "/images/blog-(1).png",
    readingMins: 4,
    category: "پربازدیدترین‌ها",
  },
  {
    id: 14,
    title: "آموزش گام به گام سوشی در خانه",
    href: "/blog/14",
    coverSrc: "/images/blog-(2).png",
    readingMins: 10,
    category: "پربازدیدترین‌ها",
  },
  {
    id: 15,
    title: "آشنایی با انواع پنیرها و کاربرد آنها",
    href: "/blog/15",
    coverSrc: "/images/blog-(3).png",
    readingMins: 8,
    category: "پربازدیدترین‌ها",
  },
  {
    id: 16,
    title: "فواید نوشیدن آب لیمو در صبح",
    href: "/blog/16",
    coverSrc: "/images/blog-(4).png",
    readingMins: 3,
    category: "پربازدیدترین‌ها",
  },
  {
    id: 17,
    title: "تفاوت قهوه عربیکا و روبوستا در چیست؟",
    href: "/blog/17",
    coverSrc: "/images/blog-(1).png",
    readingMins: 5,
    category: "پربازدیدترین‌ها",
  },
  {
    id: 18,
    title: "طرز تهیه همبرگر خانگی با گوشت تازه",
    href: "/blog/18",
    coverSrc: "/images/blog-(2).png",
    readingMins: 6,
    category: "پربازدیدترین‌ها",
  },

  // --- داغ‌ترین‌ها (Hottest) ---
  {
    id: 19,
    title: "بررسی امکانات جدید اپلیکیشن منرو",
    href: "/blog/19",
    coverSrc: "/images/blog-(3).png",
    readingMins: 3,
    category: "داغ‌ترین‌ها",
  },
  {
    id: 20,
    title: "چالش‌های تغذیه سالم در زندگی کارمندی",
    href: "/blog/20",
    coverSrc: "/images/blog-(4).png",
    readingMins: 7,
    category: "داغ‌ترین‌ها",
  },
  {
    id: 21,
    title: "معرفی ۱۰ رستوران برتر گیاهی",
    href: "/blog/21",
    coverSrc: "/images/blog-(1).png",
    readingMins: 9,
    category: "داغ‌ترین‌ها",
  },
  {
    id: 22,
    title: "چگونه هوس شیرینی را کنترل کنیم؟",
    href: "/blog/22",
    coverSrc: "/images/blog-(2).png",
    readingMins: 5,
    category: "داغ‌ترین‌ها",
  },
  {
    id: 23,
    title: "تاثیر فست‌فود بر سلامت روان",
    href: "/blog/23",
    coverSrc: "/images/blog-(3).png",
    readingMins: 6,
    category: "داغ‌ترین‌ها",
  },
  {
    id: 24,
    title: "آپدیت جدید منرو: قابلیت‌های اشتراک‌گذاری",
    href: "/blog/24",
    coverSrc: "/images/blog-(4).png",
    readingMins: 2,
    category: "داغ‌ترین‌ها",
  },
];
